<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/BrilliantMediator/BrilliantMediator.csproj" />
    <ProjectReference Include="../../../src/BrilliantMediator.SourceGenerator/BrilliantMediator.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../EcommerceDDD.Domain/EcommerceDDD.Domain.csproj" />
    <ProjectReference Include="../EcommerceDDD.Application/EcommerceDDD.Application.csproj" />
    <ProjectReference Include="../EcommerceDDD.Infrastructure/EcommerceDDD.Infrastructure.csproj" />
  </ItemGroup>

</Project>
